pipeline:
  docker:
    image: plugins/docker
    when:
      branch: master
      event: push
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/jubileuminteraktiv/jubileum
    tag: latest
